assign_badge_from_quiz.settings:
  type: config_object
  label: 'Assign Badge From Quiz settings'
  mapping:
    enabled_types:
      type: sequence
      label: 'Enabled quiz types'
      sequence:
        type: string
    html_templates:
      type: mapping
      label: 'HTML templates by type'
      mapping:
        badge_quiz:
          type: text_format
          label: 'HTML for badge_quiz'
        quiz:
          type: text_format
          label: 'HTML for quiz'
    show_badge_details:
      type: sequence
      label: 'Show detailed badge information for these quiz types'
      sequence:
        type: string
    failure_template:
      type: text_format
      label: 'HTML for failure message'
